services:
  dbms:
    image: postgres
    environment:
      TZ: ${OS_TIMEZONE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - ${DB_PORT}:5432
